version: '3'
services:
	rede_social_app:
		build:
			context: ./
			dockerfile: ./Dockerfile
		image: rede_social_app/api
		ports:
			- '8080:8080'
			- '5005:5005'
		envoriment:
			- ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_docker=y,suspend=n,adress=*:5005 -Xmx1g -Xmx128m -XX:MaxMetaspaceSize=128m
			- PROFILE=env
		links:
			- db
	db:
		image: mysql:5.6
		ports:
			- '3306:3306'
		envoriment:
			- MYSQL_ROOT_HOST=%
			- MYSQL_DATABASE=rede_social_app
			- MYSQL_USER=root
			- MYSQL_ALLOW_EMPTY_PASSWORD=yes
		volumes:
			- ./docker/volume_mysql:/var/lib/mysql 
		 